Repository 0us/IE303911-Klubbhuset, pull requests merged in 2019-11, with the labels that each got.

#49 Login should now be working
  server/src/main/java/no/ntnu/klubbhuset/ApplicationConfiguration.java
  server/src/main/java/no/ntnu/klubbhuset/RunOnStartup.java
  server/src/main/java/no/ntnu/klubbhuset/domain/SecurityGroup.java
  server/src/main/java/no/ntnu/klubbhuset/domain/User.java
  server/src/main/java/no/ntnu/klubbhuset/resource/AuthenticationResource.java
  server/src/main/java/no/ntnu/klubbhuset/resource/UserResource.java
  server/src/main/java/no/ntnu/klubbhuset/service/AuthenticationService.java
  server/src/main/java/no/ntnu/klubbhuset/service/UserService.java
Labels: bug

#61 User can join a organization
  server/src/main/java/no/ntnu/klubbhuset/RunOnStartup.java
  server/src/main/java/no/ntnu/klubbhuset/domain/Image.java
  server/src/main/java/no/ntnu/klubbhuset/domain/Organization.java
  server/src/main/java/no/ntnu/klubbhuset/resource/AuthenticationResource.java
  server/src/main/java/no/ntnu/klubbhuset/resource/OrganizationResource.java
  server/src/main/java/no/ntnu/klubbhuset/service/OrganizationService.java
  server/src/main/java/no/ntnu/klubbhuset/service/UserService.java
Labels: good first issue

#70 Docker container
  Development resources.md
  build.gradle
  server/Dockerfile
  server/README.md
  server/app.conf
  server/docker-compose.yml
  server/mysql-connector-java-5.1.48.jar
  server/mysqlconf/my.cnf
  server/src/main/java/no/ntnu/klubbhuset/DatasourceProducer.java
  server/src/main/java/no/ntnu/klubbhuset/RunOnStartup.java
  server/src/main/java/no/ntnu/klubbhuset/resource/AuthenticationResource.java
Labels: enhancement

#118 App: Repair QR-Scanner + styling #115
  app/src/main/java/no/ntnu/klubbhuset/ui/managerviews/barcode/BarcodeGraphic.java
  app/src/main/java/no/ntnu/klubbhuset/ui/managerviews/barcode/BarcodeScanningProcessor.java
  app/src/main/java/no/ntnu/klubbhuset/ui/managerviews/barcode/BarcodeViewModel.java
Labels: bug, enhancement

#121 The list of organization inside "Manage Organizations" now refreshes
  app/src/main/java/no/ntnu/klubbhuset/ui/managerviews/ManagerViewModel.java
  app/src/main/java/no/ntnu/klubbhuset/ui/managerviews/list/ManagedOrgsListFragment.java
Labels: bug, enhancement

#120 Added portait-mode only for every activity in our app.
  app/src/main/AndroidManifest.xml
Labels: enhancement

#129 Feature form validation
  app/src/main/java/no/ntnu/klubbhuset/ui/managerviews/CreateOrganizationFormFragment.java
  app/src/main/res/layout/content_club_detailed.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#131 bugfix #130
  app/src/main/java/no/ntnu/klubbhuset/MainActivity.java
  app/src/main/java/no/ntnu/klubbhuset/MasterAcitvity.java
  app/src/main/java/no/ntnu/klubbhuset/ui/login/LoginActivity.java
  app/src/main/java/no/ntnu/klubbhuset/ui/login/LoginFragment.java
  app/src/main/java/no/ntnu/klubbhuset/ui/userviews/profile/ProfileFragment.java
Labels: bug
